config/routes.rb
Rails.application.routes.draw do
  get 'help/about'

  get 'robby/index'

  get :robby, to: 'robby#index'

  devise_for :users
  get 'welcome/index'
  get 'welcome/ergo_test'

  root 'welcome#index'

  resources :communities do
    resources :joinings, to: "communities/joinings"
    resources :backgrounds, to: "communities/backgrounds"
    resources :illustrations, to: "communities/illustrations", except: %w(new)

    resources :rooms, to: "communities/rooms" do
      resources :players, to: "communities/rooms/players"

      member do
        get :playspace, to: "playroom"
        get 'playspace/main_chat_log', to: "playroom#get_main_chat_log"
        get 'playspace/illustrations', to: "playroom#get_illustrations"
        get :character_status
        get :member_statuses, to: "playroom#get_member_statuses"
      end
    end
  end

  get 'logs', to: "logs#index"
  get 'logs/result'
  get 'logs/download'

  resources :profiles, except: [:index]

  resources :characters do
    member do
      post :update_params
      post :edit_params
    end
  end
end

app/models/character.rb
# -*- coding: utf-8 -*-
# == Schema Information
#
# Table name: characters
#
#  id           :integer          not null, primary key
#  user_id      :integer
#  name         :string(255)
#  about        :string(255)
#  system_id    :integer
#  created_at   :datetime
#  updated_at   :datetime
#  paramaters   :text
#  retry_number :integer
#  profile      :text
#  memo         :text
#  image        :string(255)
#
# Indexes
#
#  index_characters_on_user_id  (user_id)
#

class Character < ActiveRecord::Base
  belongs_to :user
  has_many :players
  has_and_belongs_to_many :illustrations
  has_many :statuses, class_name: "Character::Status"

  attr_reader :system

  mount_uploader :image, CharacterUploader

  validates :user_id, :name, :system_id, presence: true

  after_initialize :set_system
  before_create :initialize_params


  def set_system
    return if self.system_id.nil?
    @system_tytle = System::TITLES.key(system_id)
    klass = Module.const_get("System::#{@system_tytle.capitalize}System")
    @system = klass.new(self, system_id)
  end

  def initialize_params
    return if @system.nil?
    self.paramaters = @system.new_character_params.to_s # 後でもう少しくらいきれいに出力する
    update_retry_number
  end

  scope :owned, ->(user_id) { where(user_id: user_id) }

  def current_status(room_id)
    unless status = self.statuses.find_by(room_id: room_id)
      status = Character::Status.create(
                             room_id: room_id,
                             character_id: self.id
                               )
    end
    status
  end

  private

  def update_retry_number
    if self.retry_number.nil?
      self.retry_number = 0
    else
      self.retry_number += 1
    end
  end
end

app/models/character/status.rb
# == Schema Information
#
# Table name: character_statuses
#
#  id              :integer          not null, primary key
#  illustration_id :integer
#  character_id    :integer
#  room_id         :integer
#  created_at      :datetime
#  updated_at      :datetime
#
# Indexes
#
#  index_character_statuses_on_character_id     (character_id)
#  index_character_statuses_on_illustration_id  (illustration_id)
#  index_character_statuses_on_room_id          (room_id)
#

class Character::Status < ActiveRecord::Base

  def self.table_name_prefix
    'character_'
  end

  belongs_to :character, dependent: :destroy
  belongs_to :room, dependent: :destroy
  belongs_to :illustration

  validates :character, :room, presence: true
end

app/controllers/characters_controller.rb
# -*- coding: utf-8 -*-
class CharactersController < ApplicationController
  layout 'mypage'
  
  before_action :set_character, only: [:show, :edit, :update, :destroy, :update_params, :edit_params]

  # GET /characters
  # GET /characters.json
  def index
    @characters = Character.owned(current_user)
  end

  # GET /characters/1
  # GET /characters/1.json
  def show
  end

  # GET /characters/new
  def new
    @character = Character.new
    @character.user = current_user
  end

  # GET /characters/1/edit
  def edit
  end

  # POST /characters
  # POST /characters.json
  def create
    @character = Character.new(character_params)

    respond_to do |format|
      if @character.save
        format.html { redirect_to @character, notice: 'Character was successfully created.' }
        format.json { render :show, status: :created, location: @character }
      else
        format.html { render :new }
        format.json { render json: @character.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /characters/1
  # PATCH/PUT /characters/1.json
  def update
    respond_to do |format|
      if @character.update(character_params)
        format.html { redirect_to @character, notice: 'Character was successfully updated.' }
        format.json { render :show, status: :ok, location: @character }
      else
        format.html { render :edit }
        format.json { render json: @character.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /characters/1
  # DELETE /characters/1.json
  def destroy
    @character.destroy
    respond_to do |format|
      format.html { redirect_to characters_url, notice: 'Character was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def update_params
    @character.initialize_params
    if @character.save
      respond_to do |format|
        format.html { render :show, notice: "パラメータを振り直しました。" } # Todo:Ajax追加
      end
    end
  end

  def edit_params
    @character.paramaters = params.permit(character: [:paramaters])
    if @character.save
      respond_to do |format|
        format.json { render @character.paramaters }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_character
      @character = Character.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def character_params
      params.require(:character).permit(:name, :about, :user_id, :system_id, :paramaters, :profile, :status, :memo, :image, :remove_image, :image_cache, illustration_ids: [])
    end
end

app/helpers/characters_helper.rb
module CharactersHelper
end

app/views/characters/_form.html.erb
<%= simple_form_for(@character) do |f| %>
  <%= f.error_notification %>

	  <div class="form-inputs">
	    <%= f.input :name %>
	    <%= f.input :about %>
	    <%= f.hint '※簡単な説明を入力してください', :class=>'margin-hint' %>
	    <%= f.input :system_id, collection: System::TITLES.sort.map {|k,v| [k, v]},:include_blank => false %>
	    <% if @character.image? %>
		    <%= image_tag  @character.image_url %>
		    <%= f.input :remove_image, label: "画像を削除", checked_value: true, unchecked_value: false  do %>
		    	<%= f.check_box :remove_image %>
	    	<% end %>
	    <% end %>
	    		    <%= f.hidden :image_cache if @character.image_cache %>

	    <%= f.input :image, as: :file, input_html: { class: 'image_load_form' } %>
	    <%= f.input :paramaters %>
	    <%= f.hint '※自動的に作成されます。内容を変更したい場合、キャラ作成後、キャラを編集し、データを上書きして保存してください。', :class=>'margin-hint' %>
	    <%= f.input :profile, as: :wysihtml5 , :input_html => {:rows => 10, cols: 100}  %>
		<%= f.hint '※簡単なHTMLタグなら有効です。', :class=>'margin-hint' %>
	    <%= f.input :memo, as: :wysihtml5 , :input_html => {:rows => 10, cols: 100}   %>
	    <%= f.hint '※簡単なHTMLタグなら有効です。', :class=>'margin-hint' %>
	    <%= f.input :user_id, as: :hidden %>
	    <%= f.input :illustration do %>
		    <%= f.select :illustration_ids, Illustration.usables(current_user).map { |f| [f.name, f.id, { 'data-img-src' => f.image_url(:thumb) }] }, { prompt: "立ち絵を選択してください" }, { multiple: true, limit: 20, class: "image-picker show-labels show-html" } %>
	    <% end %>
	    <%= f.hint '※立ち絵を選択してください。', :class=>'margin-hint' %>
	  </div>

	  <div class="form-actions">
	    <%= f.button :submit %>
	  </div>

<% end %>

<script>
$('#character_illustration_ids').imagepicker({
	hide_select: false,
	show_label: true
	});
</script>

app/views/characters/_paramaters_edit.html.erb
<%= form_tag update_params_character_path(@character) do %>
  <%= submit_tag "振り直し" %> (振り直し回数<%= @character.retry_number %>)
<% end %>

app/views/characters/edit.html.erb
<div class="container">
<h1>キャラクターの編集</h1>
<p>登録したキャラクターの編集をします。</p>
<div class="space01"></div>
<div class="row">
	<div class="col-md-offset-1 col-md-10">
		<section class="widget">
			<%= render 'form' %>
		</section>
	</div>
</div>
<div class="space01"></div>
<section class="widget">
  <ol class="breadcrumb">
    <li><%= link_to '確認', @character %></li>
	<li><%= link_to 'キャラクター一覧', characters_path %></li>
	<li><%= link_to "戻る", :back %></li>
</div>

app/views/characters/index.html.erb
<div class="container">
<h1>キャラクター一覧</h1>
<p>登録したキャラクターの一覧です。</p>
<div class="space01"></div>

<div class="row">
  <div class="col-md-offset-1 col-md-10">
    <section class="widget"> 
    <table class="table table-hover">
      <thead>
        <tr>
          <th>キャラクター名</th>
          <th>説明</th>
          <th></th>
        </tr>
      </thead>

      <tbody>
        <% @characters.each do |character| %>
          <tr>
    	<td><%= character.name %></td>
    	<td><%= character.about %></td>
            <td class="center"><%= link_to '表　示', character, :class=>"btn btn-success btn-sm"%>
            <%= link_to '編　集', edit_character_path(character), :class=>"btn btn-warning btn-sm" %>
            <%= link_to '削　除', character, method: :delete, data: { confirm: '本当に削除してよろしいですか?' }, :class=>"btn btn-danger btn-sm" %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </section>
  </div>
</div>

<div class="space01"></div>

<%= link_to '新しくキャラクターを作成する', new_character_path, :class=>"btn btn-info btn-md" %>

<div class="space01"></div>
<section class="widget">
  <ol class="breadcrumb">
    <li><%= link_to "My page", edit_user_registration_path %></li>
    <li><%= link_to "戻る", :back %></li>
  </ol>
</section>
</div>

app/views/characters/new.html.erb
<div class="container">
<h1>新しくキャラクターを登録する</h1>
<p>キャラクターを新規に作成し、登録します。</p>
<div class="space01"></div>
<div class="row">
	<div class="col-md-offset-1 col-md-10">
		<section class="widget">
			<%= render 'form' %>
		</section>
	</div>
</div>

<div class="space01"></div>
<section class="widget">
  <ol class="breadcrumb">
    <li><%= link_to 'キャラクター一覧', characters_path %></li>
    <li><%= link_to "Back", :back %></li>
  </ol>
</section>
</div>

app/views/characters/show.html.erb
<div class="container">
<h2><%= @character.name %>詳細</h2>
<p>作成したキャラクターの詳細情報です。</p>
<p id="notice"><%= notice %></p>
<div class="space01"></div>

	<div class="row">
		<div class="col-sm-offset-1 col-sm-10 col-xs-12">
			<div class="row">
				<div class="col-sm-3 col-xs-12">
					<p><%= image_tag @character.image %></p>
				</div>
				<div class="col-sm-9 col-xs-12">
					<br />
					<div class="well">
					<p><strong>パラメータ</strong></p>
					<%= @character.paramaters %>
					</div>
					<%= render :partial => "paramaters_edit" %>
					<br />	
				</div>
			</div>
			<br />
			<div class="well">
				<p><strong>キャラクター名：</strong><%= @character.name %></p>
				<p><strong>説明：</strong><%= @character.about %></p>
				<p><strong>システム：</strong><%= System::TITLES.key(@character.system_id) %></p>
			</div>

			<div class="well">
				<p><strong>立ち絵</strong></p>
				<% if @character.illustrations.count > 0 %>
					<% @character.illustrations.each do |illust| %>
						<%= image_tag illust.image_url(:thumb) %>
					<% end %>
				<% end %>
			</div>
			<div class="well">
				<strong>プロフィール</strong><br />
				<p><%= @character.profile.html_safe %></p>

				<strong>ステータス</strong><br />
				<p>後で表示</p>

				<strong>メモ</strong><br />
				<p><%= @character.memo.html_safe %></p>
			</div>
		</div>
	</div>

<div class="space01"></div>
<section class="widget">
  	<ol class="breadcrumb">
	    <li><%= link_to '編集', edit_character_path(@character) %></li>
		<li><%= link_to 'キャラクター一覧', characters_path %></li>
		<li><%= link_to "戻る", :back %></li>
	</ol>
</section>
</div>