config/routes.rb
Rails.application.routes.draw do
  get 'help/about'

  get 'robby/index'

  get :robby, to: 'robby#index'

  devise_for :users
  get 'welcome/index'
  get 'welcome/ergo_test'

  root 'welcome#index'

  resources :communities do
    resources :joinings, to: "communities/joinings"
    resources :backgrounds, to: "communities/backgrounds"
    resources :illustrations, to: "communities/illustrations", except: %w(new)

    resources :rooms, to: "communities/rooms" do
      resources :players, to: "communities/rooms/players"

      member do
        get :playspace, to: "playroom"
        get 'playspace/main_chat_log', to: "playroom#get_main_chat_log"
        get 'playspace/illustrations', to: "playroom#get_illustrations"
        get :character_status
        get :member_statuses, to: "playroom#get_member_statuses"
      end
    end
  end

  get 'logs', to: "logs#index"
  get 'logs/result'
  get 'logs/download'

  resources :profiles, except: [:index]

  resources :characters do
    member do
      post :update_params
      post :edit_params
    end
  end
end

app/controllers/communities/backgrounds_controller.rb
class Communities::BackgroundsController < ApplicationController
  before_action :set_background, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate_user!

layout "playroom"
  # GET /backgrounds
  # GET /backgrounds.json
  def index
    @community = Community.find(params[:community_id])
    @backgrounds = @community.backgrounds

  end

  # GET /backgrounds/1
  # GET /backgrounds/1.json
  def show
  end

  # GET /backgrounds/new
  def new
    @community = Community.find(params[:community_id])
    @background = Background.new
  end

  # GET /backgrounds/1/edit
  def edit
  end

  # POST /backgrounds
  # POST /backgrounds.json
  def create
    @background = Background.new(background_params)
    @community =  Community.find(params[:community_id])
    @background.community = @community
    @background.user = current_user

    respond_to do |format|
      if @background.save
        format.html { redirect_to [@community, @background], notice: 'Background was successfully created.' }
        format.json { render :show, status: :created, location: @background }
      else
        format.html { render :new }
        format.json { render json: @background.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /backgrounds/1
  # PATCH/PUT /backgrounds/1.json
  def update
    respond_to do |format|

      if @background.update(background_params)
        format.html { redirect_to [@community, @background], notice: 'Background was successfully updated.' }
        format.json { render :show, status: :ok, location: @background }
      else
        format.html { render :edit }
        format.json { render json: @background.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /backgrounds/1
  # DELETE /backgrounds/1.json
  def destroy
    @background.destroy
    respond_to do |format|
      format.html { redirect_to backgrounds_url, notice: 'Background was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_background
      @background = Background.find(params[:id])
      @community = Community.find(params[:community_id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def background_params
      params.require(:background).permit(:room_id, :image, :name, :about, :user_id, :access, :community_id)
    end
end

app/controllers/communities/illustrations_controller.rb
class Communities::IllustrationsController < ApplicationController
  before_action :set_communities_illustration, only: [:show, :edit, :update, :destroy]
  before_action :set_community

  before_filter :authenticate_user!

  # GET /communities/illustrations
  # GET /communities/illustrations.json
  def index
    @illustration =Illustration.new
    @illustrations =Illustration.all
  end

  # GET /communities/illustrations/1
  # GET /communities/illustrations/1.json
  def show
  end

  # GET /communities/illustrations/1/edit
  def edit
  end

  # POST /communities/illustrations
  # POST /communities/illustrations.json
  def create
    @illustration = Illustration.new(illustration_params)
    @illustration.user = current_user

    respond_to do |format|
      if @illustration.save
        format.html { redirect_to [@community, @illustration], notice: 'Illustration was successfully created.' }
        format.json { render :show, status: :created }
      else
        format.html { render :new }
        format.json { render json: @illustration.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /communities/illustrations/1
  # PATCH/PUT /communities/illustrations/1.json
  def update
    respond_to do |format|
      if @illustration.update(illustration_params)
        format.html { redirect_to [@community, @illustration], notice: 'Illustration was successfully updated.' }
        format.json { render :show, status: :ok, location: [@community, @illustration] }
      else
        format.html { render :edit }
        format.json { render json: @illustration.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /communities/illustrations/1
  # DELETE /communities/illustrations/1.json
  def destroy
    @illustration.destroy
    respond_to do |format|
      format.html { redirect_to community_illustrations_url(@community), notice: 'Illustration was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
  def set_communities_illustration
    set_community
    @illustration =Illustration.find(params[:id])
  end

  def set_community
    @community = Community.find(params[:community_id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def illustration_params
    params.require(:illustration).permit(:name, :description, :image, :access, :character_id)
  end
end

app/controllers/communities/joinings_controller.rb
# -*- coding: utf-8 -*-
class Communities::JoiningsController < ApplicationController
  before_filter :authenticate_user!
  before_action :set_communities_joining, only: [:show, :edit, :update, :destroy]
  before_action :set_community, only: [:index, :new, :create]

  # cancanを入れたらcreateでひっかかったので、https://github.com/ryanb/cancan/issues/835の方法で回避
  load_and_authorize_resource through: :community, except: [:create]

  # GET /communities/joinings
  # GET /communities/joinings.json
  def index
    @community = Community.find(params[:community_id])
    @communities_joinings =Joining.where(community_id: @community.id)
  end

  # GET /communities/joinings/1
  # GET /communities/joinings/1.json
  def show
  end

  # GET /communities/joinings/new
  def new
    @communities_joining =Joining.new
  end

  # GET /communities/joinings/1/edit
  def edit
  end

  # POST /communities/joinings
  # POST /communities/joinings.json
  def create
    @communities_joining = Joining.new(communities_joining_params)

    @communities_joining.community = @community
    @communities_joining.user_id = current_user.id
    @communities_joining.role = Role.find_by(name: 'member')

    respond_to do |format|
      if @communities_joining.save
        format.html { redirect_to @community, notice: "#{@community.name}に参加を申し込みました！" }
        format.json { render :show, status: :created, location: @communities_joining }
      else
        @community = Community.find params[:community_id]
        format.html { render :new }
        format.json { render json: @communities_joining.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /communities/joinings/1
  # PATCH/PUT /communities/joinings/1.json
  def update
    respond_to do |format|
      if @communities_joining.update(communities_joining_params)
        format.html { redirect_to @community, notice: 'メンバーを変更しました' }
        format.json { render :show, status: :ok, location: @communities_joining }
      else
        format.html { render :edit }
        format.json { render json: @communities_joining.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /communities/joinings/1
  # DELETE /communities/joinings/1.json
  def destroy
    @communities_joining.destroy
    respond_to do |format|
      format.html { redirect_to community_joinings_path(params[:community_id]), notice: 'メンバーは削除されました' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_communities_joining
      @communities_joining = Joining.find(params[:id])
      @community = Community.find(params[:community_id])
    end

    def set_community
      @community = Community.find(params[:community_id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def communities_joining_params
     params.require(:joining).permit(:comment, :role_id)
    end
end

app/controllers/communities/maps_controller.rb
# -*- coding: utf-8 -*-
class Communities::MapsController < ApplicationController
  before_filter :authenticate_user!
  before_action :set_map, only: [:show, :edit, :update, :destroy]
  before_action :set_community

  # GET /communities/maps
  # GET /communities/maps.json
  def index
    @maps = Map.available(current_user)
  end

  # GET /communities/maps/1
  # GET /communities/maps/1.json
  def show
  end

  # GET /communities/maps/new
  def new
    @map = Map.new
  end

  # GET /communities/maps/1/edit
  def edit
  end

  # POST /communities/maps
  # POST /communities/maps.json
  def create
    @map = Map.new(map_params)
    @map.community = @community
    @map.user = current_user

    respond_to do |format|
      if @map.save
        format.html { redirect_to [@community, @map], notice: 'マップを作成しました。' }
        format.json { render :show, status: :created, location: @map }
      else
        format.html { render :new }
        format.json { render json: @map.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /communities/maps/1
  # PATCH/PUT /communities/maps/1.json
  def update
    respond_to do |format|
      if @map.update(map_params)
        format.html { redirect_to [@community, @map], notice: 'マップを更新しました。' }
        format.json { render :show, status: :ok, location: [@community, @map] }
      else
        format.html { render :edit }
        format.json { render json: @map.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /communities/maps/1
  # DELETE /communities/maps/1.json
  def destroy
    @map.destroy
    respond_to do |format|
      format.html { redirect_to community_maps_url(@community), notice: 'マップを削除しました' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_map
      @map = Map.find(params[:id])
    end

    def set_community
      @community = Community.find(params[:community_id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def map_params
      params.require(:map).permit(:title, :about, :description, :image, :access)
    end
end

app/controllers/communities/rooms/players_controller.rb
# -*- coding: utf-8 -*-
class Communities::Rooms::PlayersController < ApplicationController
  before_filter :authenticate_user!, except: [:index, :show]

  before_action :set_player, only: [:show, :edit, :update, :destroy]
  before_action :set_community_and_rooms, only: [:new, :create, :index]


  load_and_authorize_resource :room
  load_and_authorize_resource :player, through: :room

  # GET /communities/rooms/players
  # GET /communities/rooms/players.json
  def index
    @players = @room.players
  end

  # GET /communities/rooms/players/1
  # GET /communities/rooms/players/1.json
  def show
  end

  # GET /communities/rooms/players/new
  def new
    @player = Player.new
    @player.user = current_user
    @player.room = @room
  end

  # GET /communities/rooms/players/1/edit
  def edit
  end

  # POST /communities/rooms/players
  # POST /communities/rooms/players.json
  def create
    @player = Player.new(player_params)
    @player.user = current_user
    @player.room = @room

    respond_to do |format|
      if @player.save
        format.html { redirect_to [@community, @room, @player], notice: 'Player was successfully created.' }
        format.json { render :show, status: :created, location: @player }
      else
        format.html { render :new }
        format.json { render json: @player.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /communities/rooms/players/1
  # PATCH/PUT /communities/rooms/players/1.json
  def update
    respond_to do |format|
      if @player.update(player_params)
        format.html { redirect_to [@community, @room, @player], notice: 'Player was successfully updated.' }
        format.json { render :show, status: :ok, location: @communities_rooms_player }
      else
        format.html { render :edit }
        format.json { render json: @communities_rooms_player.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /communities/rooms/players/1
  # DELETE /communities/rooms/players/1.json
  def destroy
    @player.destroy
    respond_to do |format|
      format.html { redirect_to community_room_players_url(@community, @room), notice: '参加を辞退しました' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_player
      @community = Community.find(params[:community_id])
      @room = Room.find(params[:room_id])
      @player = Player.find(params[:id])
    end

    def set_community_and_rooms
      @community = Community.find(params[:community_id])
      @room = Room.find(params[:room_id])
    end
    # Never trust parameters from the scary internet, only allow the white list through.
    def player_params
      params.require(:player).permit(:player_role_id, :character_id, :room_id)
    end
end

app/controllers/communities/rooms_controller.rb
class Communities::RoomsController < ApplicationController
  before_action :set_room, only: [:show, :edit, :update, :destroy, :playspace, :character_status]
  before_action :set_community

  before_filter :authenticate_user!, except: [:index]

  # load_and_authorize_resource :community
  # load_and_authorize_resource :room, :through => :community, :shallow => true
  load_and_authorize_resource through: :community

  # GET /communities/rooms
  # GET /communities/rooms.json
  def index
    @rooms =Room.where(community: @community)
  end

  # GET /communities/rooms/1
  # GET /communities/rooms/1.json
  def show
  end

  # GET /communities/rooms/new
  def new
    @room =Room.new
    @room.community = @community
  end

  # GET /communities/rooms/1/edit
  def edit
  end

  # POST /communities/rooms
  # POST /communities/rooms.json
  def create
    @room =Room.new(room_params)
    @room.owner = current_user

    respond_to do |format|
      if @room.save
        format.html { redirect_to [@community, @room], notice: 'Room was successfully created.' }
        format.json { render :show, status: :created, location: @room }
      else
        format.html { render :new }
        format.json { render json: @room.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /communities/rooms/1
  # PATCH/PUT /communities/rooms/1.json
  def update
    respond_to do |format|
      if @room.update(room_params)
        format.html { redirect_to [@community, @room], notice: 'Room was successfully updated.' }
        format.json { render :show, status: :ok, location: @room }
      else
        format.html { render :edit }
        format.json { render json: @room.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /communities/rooms/1
  # DELETE /communities/rooms/1.json
  def destroy
    @room.destroy
    respond_to do |format|
      format.html { redirect_to community_rooms_path(@community), notice: 'Room was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def character_status
    if params[:user_id]
      @character = @room.character(User.find(params[:user_id]))
    else
      @character = @room.character(current_user)
    end

        html = render_to_string partial: 'playroom/character_status', collection: [@character]
        render html: html
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_room
      @room =Room.find(params[:id])
    end

    def set_community
      @community = Community.find(params[:community_id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def room_params
      params.require(:room).permit(:name, :about, :started_at, :community_id, :system_id, :active_background_id)
    end
end

app/helpers/communities/illustrations_helper.rb
module Communities::IllustrationsHelper
end

app/helpers/communities/joinings_helper.rb
module Communities::JoiningsHelper
end

app/helpers/communities/maps_helper.rb
module Communities::MapsHelper
end

app/helpers/communities/rooms/players_helper.rb
module Communities::Rooms::PlayersHelper
end

app/helpers/communities/rooms_helper.rb
module Communities::RoomsHelper
end

app/helpers/communities/scenarios_helper.rb
module Communities::ScenariosHelper
end

app/helpers/communities_helper.rb
module CommunitiesHelper
end

app/views/communities/rooms/_form.html.erb
<%= simple_form_for([@community, @room]) do |f| %>
  <% if @room.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@room.errors.count, "error") %> prohibited this room from being saved:</h2>

      <ul>
      <% @room.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>

  <% end %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :community_id, as: :hidden %>
    <%= f.input :about %>
	  <%= f.input :system_id, collection: System::TITLES %>
    <%= f.hint '※ダイスシステムを選択してください。', :class=>'margin-hint' %>
	  <%= f.input :active_background_id, collection: Background.where(room: @room) %>
    <%= f.input :started_at,  as: :date, input_html: { class: 'size_days' }, label_html: { class: 'size_lavel' }  %>
  </div>
  <div class="space01"></div>
  <div class="form-actions">
    <%= f.button :submit, :class=>"btn btn-default" %>
  </div>
  <% end %>

app/views/communities/rooms/_settings.html.erb
<!-- シナリオ等 -->
<%= link_to "新規シナリオを作成する", new_community_scenario_path(@community, room_id: @room.id, system: @room.system_id) %>

app/views/communities/rooms/edit.html.erb
<div class="container">
<h1>セッションルームの編集</h1>
<p>セッションルームの編集を行います。</p>
<div class="space01"></div>
<div class="row">
	<div class="col-md-offset-1 col-md-10">
		<section class="widget">
			<%= render 'form' %>
            <br>
            <%= render "settings" %>
		</section>
	</div>
</div>
<div class="space01"></div>
<section class="widget">
 	<ol class="breadcrumb">
		<li><%= link_to '確認', [@community, @room] %></li>
		<li><%= link_to "戻る", :back %></li>
	</ol>
</section>
</div>

app/views/communities/rooms/index.html.erb
<div class="container">
<h1><%= @community.name %>のセッションルーム一覧</h1>
<p>コミュニティ『<%= @community.name %>』が作成したセッションルームの一覧です。</p>

<div class="space01"></div>

<section class="widget">
    <table class="table table-hover">
      <thead>
        <tr>
          <th>セッションルーム名</th>
          <th>ルームオーナー</th>
          <th>説明</th>
          <th></th>
        </tr>
      </thead>

      <tbody>
        <% @rooms.each do |room| %>
          <tr>
        	<td><%= link_to room.name, [@community, room] %>
		  <% if (can? :create, Player) && !room.has_member?(current_user) %>
        	    <%= link_to 'このセッションに参加する', new_community_room_player_path(@community, room), :class=>"btn btn-primary btn-xs" %></td>
		<% end %>
        	<td><%= room.owner.name %></td>
        	<td><%= room.about %>
		  <% if can? :playspace, room %>
		    <%= link_to 'セッションルームへ', playspace_community_room_path(@community, room), :class=>"btn btn-primary btn-xs", data: { no_turbolink: true } %>
		  <% end %>
		</td>
          <td class="center">
            <%= link_to '表　示', [@community, room], :class=>"btn btn-success btn-sm" %>
	    <% if can? :manage, @room %>
              <%= link_to '編　集', edit_community_room_path(@community, room), :class=>"btn btn-warning btn-sm" %>
              <%= link_to '削　除', [@community, room], method: :delete, data: { confirm: '本当に削除してもよろしいですか？' }, :class=>"btn btn-danger btn-sm" %>
	    <% end %>
          </td>
          </tr>
        <% end %>
      </tbody>
    </table>
</section>

<div class="space01"></div>

<%= link_to '新しくセッションルームを作成する', new_community_room_path, :class=>"btn btn-info" %>

<div class="space01"></div>
<section class="widget">
  <ol class="breadcrumb">
    <li><%= link_to 'コミュニティーTOP', @community %></li>
    <li><%= link_to "戻る", :back %></li>
  </ol>
</section>
</div>

app/views/communities/rooms/new.html.erb
<div class="container">
<h1>新しくセッションルームを作成する</h1>
<p>新しいセッションルームを作成します。</p>
<div class="space01"></div>
<div class="row">
	<div class="col-md-offset-1 col-md-10">
		<section class="widget">
			<%= render 'form' %>
            <br>
            <%= render "settings" %>
		</section>
	</div>
</div>

<div class="space01"></div>
<section class="widget">
 	<ol class="breadcrumb">
		<li><%= link_to 'セッションルーム一覧', community_rooms_path(@community) %></li>
		<li><%= link_to "戻る", :back %></li>
	</ol>
</section>
</div>

app/views/communities/rooms/playspace.html.erb
<section class="room">
<div id="wrapper">
	<div class="container-fluid fluid menu-left">
		<div id="menu" class="hidden-phone hidden-print">
			
			<!-- Scrollable menu wrapper with Maximum height -->
			<div class="slim-scroll" data-scroll-height="800px">
			
				<!-- Sidebar Profile -->
				<span class="profile">
					<p>Welcome <a href="my_account.html?lang=en&amp;layout_type=fluid&amp;menu_position=menu-left&amp;style=style-light"><%= current_user.name %></strong></p></a>
					<a class="img" href="my_account.html?lang=en&amp;layout_type=fluid&amp;menu_position=menu-left&amp;style=style-light"><%= image_tag("ergo/avatar-style-light.jpg") %>
					</a>
					<span>
						<ul>
							<li><a href="" class="glyphicons lock"><i></i>Account</a></li>
							<li><a href="" class="glyphicons keys"><i></i>Password</a></li>
							<li><a href="" class="glyphicons eject"><i></i>Logout</a></li>
						</ul>
					</span>
				</span>
				<!-- // Sidebar Profile END -->
				
				<!-- Regular Size Menu -->
				<ul class="menu-0">
					
					<!-- Components Submenu Level 1 -->
					<li class="hasSubmenu glyphicons user active">
						<a data-toggle="collapse" href="#menu_components"><i></i><span>My Status</span></a>
						<ul class="collapse in" id="menu_components">

							<!-- Components Submenu Regular Items -->
							<li class=""><p class="status">ここにステータスとか書いていけないかな</p><p class="status">テストテスト</p></li>
							<!-- // Components Submenu Regular Items END -->
							
							<!-- Components Submenu Level 2 -->
							<li class="hasSubmenu active">
								<a data-toggle="collapse" href="#menu_forms"><span>skill</span></a>
								<ul class="collapse in" id="menu_forms">
									<li class=""><a href="form_wizards.html?lang=en&amp;layout_type=fluid&amp;menu_position=menu-left&amp;style=style-light"><span>sample1-1</span></a></li>
								</ul>
								<span class="count">1</span>
							</li>
							<!-- // Components Submenu Level 2 END -->

							<!-- Components Submenu Level 2 -->
							<li class="hasSubmenu">
								<a data-toggle="collapse" href="#menu_tables"><span>memo</span></a>
								<ul class="collapse" id="menu_tables">
									<li class=""><a href="tables.html?lang=en&amp;layout_type=fluid&amp;menu_position=menu-left&amp;style=style-light"><span>sample2-2</span></a></li>
								</ul>
								<span class="count">1</span>
							</li>
							<!-- // Components Submenu Level 2 -->
							
						</ul>
						<span class="count">test</span>
					</li>
					<!-- Components Submenu Level 1 END -->

					<!-- Components Submenu Level 1 -->
					<li class="hasSubmenu glyphicons group active">
						<a data-toggle="collapse" href="#menu_member"><i></i><span>Member</span></a>
							<ul class="collapse" id="menu_member">
								
								<!-- Components Submenu Regular Items -->
								<li class="hasSubmenu"><a href="grid.html?lang=en&amp;layout_type=fluid&amp;menu_position=menu-left&amp;style=style-light"><span>Member Name</span></a></li>
								<!-- // Components Submenu Regular Items END -->
							</ul>
						<span class="count">1</span>
					</li>
					<!-- Components Submenu Level 1 END -->

					<!-- Menu Regular Item -->
					<li class="glyphicons comments"><a href="index.html?lang=en&amp;layout_type=fluid&amp;menu_position=menu-left&amp;style=style-light"><i></i><span>Member Chat</span></a></li>
					
					<!-- Menu Regular Item -->
					<li class="glyphicons notes"><a href="index.html?lang=en&amp;layout_type=fluid&amp;menu_position=menu-left&amp;style=style-light"><i></i><span>Public Memo</span></a></li>

					<!-- Components Submenu Level 1 -->
					<li class="hasSubmenu glyphicons playing_dices active">
						<a data-toggle="collapse" href="#menu_master"><i></i><span>Master Menu</span></a>
						<ul class="collapse in" id="menu_master">
							
							<!-- Components Submenu Regular Items -->
							<li class=""><a href="ui.html?lang=en&amp;layout_type=fluid&amp;menu_position=menu-left&amp;style=style-light"><span>シナリオ管理</span></a></li>
							<li class=""><a href="ui.html?lang=en&amp;layout_type=fluid&amp;menu_position=menu-left&amp;style=style-light"><span>NPC管理</span></a></li>
							<li class=""><a href="ui.html?lang=en&amp;layout_type=fluid&amp;menu_position=menu-left&amp;style=style-light"><span>マップ表示</span></a></li>

							<!-- Components Submenu Level 2 -->
							<li class="hasSubmenu">
								<a data-toggle="collapse" href="#menu_mastersub"><span>演出</span></a>
								<ul class="collapse in" id="menu_mastersub">
									<li class=""><a href="form_wizards.html?lang=en&amp;layout_type=fluid&amp;menu_position=menu-left&amp;style=style-light"><span>背景変更</span></a></li>
									<li class=""><a href="form_wizards.html?lang=en&amp;layout_type=fluid&amp;menu_position=menu-left&amp;style=style-light"><span>動画表示</span></a></li>
									<li class=""><a href="form_wizards.html?lang=en&amp;layout_type=fluid&amp;menu_position=menu-left&amp;style=style-light"><span>BGM・SE</span></a></li>
								</ul>
								<span class="count">3</span>
							</li>
							<!-- // Components Submenu Level 2 END -->
							
						</ul>
						<span class="count">4</span>
					</li>
					<!-- Components Submenu Level 1 END -->
										
				</ul>
				<div class="clearfix"></div>
				<!-- // Regular Size Menu END -->				
			</div>
			<!-- // Scrollable Menu wrapper with Maximum Height END -->				
		</div>
		<!-- // Sidebar Menu END -->
					
		<!-- Content -->
		<div id="content">
			<h1>プレイルーム</h1>
			<p>セッションページです。</p>
			<div class="space01"></div>
			<%= hidden_field :room, :id, value: @room.id %>

			<%= render "chat/chat_form" %>
			<div class="space01"></div>
			<p><%= link_to "Home", welcome_index_path %>｜<%= link_to "Back", :back %></p>
			<div class="space01"></div>
		</div>

	</div>
</div>
</section>

app/views/communities/rooms/show.html.erb
<!-- <p id="notice"><%= notice %></p> -->
<div class="container">

<div class="row">
  <div class="col-md-offset-2 col-md-8 col-xs-12">
    <section class="widget">	
		<legend><%= @room.name %>　<small>オーナー：<%= @room.owner.name %></small>
		  <% if can? :manage, @room %>
		  	<%= link_to 'ルームの編集', edit_community_room_path(@community, @room), :class=>"btn btn-warning btn-xs pull-right" %> 
		<% end %>
		</legend>
		<p><%= @room.about %></p>
		<% if cannot? :playspace, @room %>
			<div class="space01"></div>
			<legend class="section">セッションを始める・見るにはまずここからメンバー登録！</legend>
			<div class="row">
	  			<div class="col-md-offset-2 col-md-8 col-xs-12">
					<%= link_to 'このセッションに参加する', new_community_room_player_path(@community, @room), :class=>"btn btn-primary btn-block" %>
				</div>
			</div>			
		<% end %>


		<div class="space01"></div>
		<legend class="section">セッション参加者の確認、キャラシートの確認はここから</legend>
		<div class="row">
  			<div class="col-md-offset-2 col-md-8 col-xs-12">
				<%= link_to "参加者一覧", community_room_players_path(@community, @room), :class=>"btn btn-inverse btn-block" %>
			</div>
		</div>
		<% if  can? :playspace, @room %>
			<div class="space01"></div>
			<legend class="section">セッションを始める時はここから</legend>
			<div class="row">
	  			<div class="col-md-offset-2 col-md-8 col-xs-12">
					<%= link_to "セッションルームへ", playspace_community_room_path(@community, @room), :class=>"btn btn-success btn-block", data: {no_turbo_link: true} %>
				</div>
			</div>			
		<% end %>


		<div class="space01"></div>
	</section>
	</div>
</div>	

	<div class="space01"></div>
	<section class="widget">
 		<ol class="breadcrumb">
			<li><%= link_to 'セッションルーム一覧', community_rooms_path(@community) %></li>
			<li><%= link_to "戻る", :back %></li>
		</ol>
	</section>
	
</div>