config/routes.rb
Rails.application.routes.draw do
  get 'help/about'

  get 'robby/index'

  get :robby, to: 'robby#index'

  devise_for :users
  get 'welcome/index'
  get 'welcome/ergo_test'

  root 'welcome#index'

  resources :communities do
    resources :joinings, to: "communities/joinings"
    resources :backgrounds, to: "communities/backgrounds"
    resources :illustrations, to: "communities/illustrations", except: %w(new)

    resources :rooms, to: "communities/rooms" do
      resources :players, to: "communities/rooms/players"

      member do
        get :playspace, to: "playroom"
        get 'playspace/main_chat_log', to: "playroom#get_main_chat_log"
        get 'playspace/illustrations', to: "playroom#get_illustrations"
        get :character_status
        get :member_statuses, to: "playroom#get_member_statuses"
      end
    end
  end

  get 'logs', to: "logs#index"
  get 'logs/result'
  get 'logs/download'

  resources :profiles, except: [:index]

  resources :characters do
    member do
      post :update_params
      post :edit_params
    end
  end
end

app/models/player.rb
# -*- coding: utf-8 -*-
# == Schema Information
#
# Table name: players
#
#  id             :integer          not null, primary key
#  user_id        :integer
#  room_id        :integer
#  player_role_id :integer
#  character_id   :integer
#  created_at     :datetime
#  updated_at     :datetime
#
# Indexes
#
#  index_players_on_character_id    (character_id)
#  index_players_on_player_role_id  (player_role_id)
#  index_players_on_user_id         (user_id)
#

class Player < ActiveRecord::Base
  belongs_to :user, inverse_of: :players
  belongs_to :player_role
  belongs_to :character
  belongs_to :room, inverse_of: :players

  validates :user, :room, :player_role, presence: true
  validates :user,  uniqueness: { scope: :room }
  validate :only_player_has_character

  def only_player_has_character
    player_role = PlayerRole.find(player_role_id)

    errors.add(:character_id, "：　キャラクターを使用できるのはプレイヤーのみです") if player_role.name != 'player' && character_id.present?
  end
end

app/models/room.rb
# -*- coding: utf-8 -*-
# == Schema Information
#
# Table name: rooms
#
#  id                   :integer          not null, primary key
#  name                 :string(255)
#  about                :string(255)
#  owner_id             :integer          not null
#  system_id            :integer          default(0)
#  community_id         :integer          not null
#  started_at           :datetime
#  finished_at          :datetime
#  created_at           :datetime
#  updated_at           :datetime
#  active_background_id :integer
#  scenario_id          :integer
#
# Indexes
#
#  index_rooms_on_community_id  (community_id)
#  index_rooms_on_owner_id      (owner_id)
#  index_rooms_on_scenario_id   (scenario_id)
#

class Room < ActiveRecord::Base
  include Redis::Objects

  belongs_to :community
  belongs_to :owner, class_name: "User", foreign_key: :owner_id
  has_many :players
  has_many :users, through: :players
  has_many :backgrounds
  belongs_to :scenario
  belongs_to :active_background, class_name: "Background", foreign_key: :active_background_id

  value :stored_dice

  validates :name, :about, :community, :owner, :system_id, presence: true

  attr_reader :dice, :system

  after_initialize :initialize_system
  after_create :initialize_dice
  after_update :change_system, if: Proc.new { |a| a.system_id_changed? }


  def initialize_system
    set_system
    initialize_dice unless self.id.nil?         # new直後は実行しない
  end

  def change_system
    set_system
    @dice = @system.dice
    store_dice
  end

  def initialize_dice
    if stored_dice.nil?
      @dice = @system.dice
      store_dice
    else
      @dice = Marshal.load(stored_dice)
    end
  end

  def store_dice
    stored_dice = Marshal.dump(@dice)
  end

  def owned?(user)
    self.owner == user
  end

  def has_member?(user)
    self.players.where(user_id: user.id).length > 0
  end

  def character(user)
    if player = self.players.find_by(user_id: user.id)
      player.character
    end
  end

  def play_role(user)
    if player = self.players.find_by(user_id: user.id)
      player.player_role
    end
  end

  scope :downloadable, ->(user_id) { where{created_at >= Date.today - 50.days}
      .joins(community: :users).where{users.id.eq user_id} } # 50日以内のみログダウンロード可

  private
  def set_system
    @system_tytle = System::TITLES.key(system_id)
    klass = Module.const_get("System::#{@system_tytle.capitalize}System")
    @system = klass.new(self, system_id)
  end
end

app/controllers/communities/rooms/players_controller.rb
# -*- coding: utf-8 -*-
class Communities::Rooms::PlayersController < ApplicationController
  before_filter :authenticate_user!, except: [:index, :show]

  before_action :set_player, only: [:show, :edit, :update, :destroy]
  before_action :set_community_and_rooms, only: [:new, :create, :index]


  load_and_authorize_resource :room
  load_and_authorize_resource :player, through: :room

  # GET /communities/rooms/players
  # GET /communities/rooms/players.json
  def index
    @players = @room.players
  end

  # GET /communities/rooms/players/1
  # GET /communities/rooms/players/1.json
  def show
  end

  # GET /communities/rooms/players/new
  def new
    @player = Player.new
    @player.user = current_user
    @player.room = @room
  end

  # GET /communities/rooms/players/1/edit
  def edit
  end

  # POST /communities/rooms/players
  # POST /communities/rooms/players.json
  def create
    @player = Player.new(player_params)
    @player.user = current_user
    @player.room = @room

    respond_to do |format|
      if @player.save
        format.html { redirect_to [@community, @room, @player], notice: 'Player was successfully created.' }
        format.json { render :show, status: :created, location: @player }
      else
        format.html { render :new }
        format.json { render json: @player.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /communities/rooms/players/1
  # PATCH/PUT /communities/rooms/players/1.json
  def update
    respond_to do |format|
      if @player.update(player_params)
        format.html { redirect_to [@community, @room, @player], notice: 'Player was successfully updated.' }
        format.json { render :show, status: :ok, location: @communities_rooms_player }
      else
        format.html { render :edit }
        format.json { render json: @communities_rooms_player.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /communities/rooms/players/1
  # DELETE /communities/rooms/players/1.json
  def destroy
    @player.destroy
    respond_to do |format|
      format.html { redirect_to community_room_players_url(@community, @room), notice: '参加を辞退しました' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_player
      @community = Community.find(params[:community_id])
      @room = Room.find(params[:room_id])
      @player = Player.find(params[:id])
    end

    def set_community_and_rooms
      @community = Community.find(params[:community_id])
      @room = Room.find(params[:room_id])
    end
    # Never trust parameters from the scary internet, only allow the white list through.
    def player_params
      params.require(:player).permit(:player_role_id, :character_id, :room_id)
    end
end

app/controllers/communities/rooms_controller.rb
class Communities::RoomsController < ApplicationController
  before_action :set_room, only: [:show, :edit, :update, :destroy, :playspace, :character_status]
  before_action :set_community

  before_filter :authenticate_user!, except: [:index]

  # load_and_authorize_resource :community
  # load_and_authorize_resource :room, :through => :community, :shallow => true
  load_and_authorize_resource through: :community

  # GET /communities/rooms
  # GET /communities/rooms.json
  def index
    @rooms =Room.where(community: @community)
  end

  # GET /communities/rooms/1
  # GET /communities/rooms/1.json
  def show
  end

  # GET /communities/rooms/new
  def new
    @room =Room.new
    @room.community = @community
  end

  # GET /communities/rooms/1/edit
  def edit
  end

  # POST /communities/rooms
  # POST /communities/rooms.json
  def create
    @room =Room.new(room_params)
    @room.owner = current_user

    respond_to do |format|
      if @room.save
        format.html { redirect_to [@community, @room], notice: 'Room was successfully created.' }
        format.json { render :show, status: :created, location: @room }
      else
        format.html { render :new }
        format.json { render json: @room.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /communities/rooms/1
  # PATCH/PUT /communities/rooms/1.json
  def update
    respond_to do |format|
      if @room.update(room_params)
        format.html { redirect_to [@community, @room], notice: 'Room was successfully updated.' }
        format.json { render :show, status: :ok, location: @room }
      else
        format.html { render :edit }
        format.json { render json: @room.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /communities/rooms/1
  # DELETE /communities/rooms/1.json
  def destroy
    @room.destroy
    respond_to do |format|
      format.html { redirect_to community_rooms_path(@community), notice: 'Room was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def character_status
    if params[:user_id]
      @character = @room.character(User.find(params[:user_id]))
    else
      @character = @room.character(current_user)
    end

        html = render_to_string partial: 'playroom/character_status', collection: [@character]
        render html: html
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_room
      @room =Room.find(params[:id])
    end

    def set_community
      @community = Community.find(params[:community_id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def room_params
      params.require(:room).permit(:name, :about, :started_at, :community_id, :system_id, :active_background_id)
    end
end

app/controllers/room_controller.rb
# -*- coding: utf-8 -*-
class RoomController < WebsocketRails::BaseController

  def background_changed
    puts "called background_changed"
    room = Room.find(message[:room_id])
    room.active_background = Background.find(message[:background_id])
    if room.save
      message[:background_url] = room.active_background.image_url
      WebsocketRails["room_#{message[:room_id]}"].trigger(:background_changed, message)
      puts "changed"
    end
  end
end

app/helpers/communities/rooms/players_helper.rb
module Communities::Rooms::PlayersHelper
end

app/helpers/communities/rooms_helper.rb
module Communities::RoomsHelper
end

app/views/communities/rooms/players/_form.html.erb
<%= simple_form_for([@community, @room, @player]) do |f| %>
  <%= f.error_notification %>
<%= render 'common/error_messages', object: f.object %>

  <div class="form-inputs">
    <%= f.input :room_id, as: :hidden %>
    <%= f.input :player_role_id, collection: PlayerRole.all %>
    <%= f.input :character_id, collection: Character.owned(current_user)%>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
  <% end %>

app/views/communities/rooms/players/edit.html.erb
<div class="container">
<h1>プレイヤーの編集</h1>
<p>参加するキャラクターを変更したり、役割を変えたりします。</p>
<div class="space01"></div>
<div class="row">
	<div class="col-md-offset-1 col-md-10">
		<section class="widget">
			<%= render 'form' %>
		</section>
	</div>
</div>
<div class="space01"></div>
<section class="widget">
 	<ol class="breadcrumb">
		<li><%= link_to '確認', [@community, @room, @player] %></li>
		<li><%= link_to "セッション参加者一覧", community_room_players_path(@community, @room) %></li>
		<li><%= link_to "戻る", :back %></li>
	</ol>
</section>
</div>

app/views/communities/rooms/players/index.html.erb
<div class="container">
<h1><%= @room.name %>参加者一覧</h1>
<p><%= @room.name %>の参加者一覧です</p>

<div class="space01"></div>

<div class="row">
  <div class="col-md-offset-1 col-md-10">
    <section class="widget">
      <table class="table table-hover">
          <thead>
            <tr>
              <th>ユーザー名</th>
              <th>役割</th>
              <th>キャラクター名</th>
              <th></th>
            </tr>
          </thead>

          <tbody>
            <% @players.each do |player| %>
              <tr>
              	<td><%= player.user.name %></td>
              	<td><%= player.player_role.name %></td>
              	<td><%= player.character.name unless player.character.nil? %></td>
                <td class="center"><%= link_to '確　認', [@community, @room, player], :class=>"btn btn-success btn-sm" %>
                <%= link_to '参加辞退', [@community, @room, player], method: :delete, data: { confirm: '本当に参加をやめますか？' }, :class=>"btn btn-danger btn-sm" %></td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </section>
    </div>
  </div>
  
<div class="space01"></div>

<%= link_to 'このセッションに参加する', new_community_room_player_path(@community, @room), :class=>"btn btn-primary btn-lg" %>

<div class="space01"></div>
<section class="widget">
  <ol class="breadcrumb">
    <li><%= link_to 'セッションルームTop', community_room_path(@community, @room) %></li>
    <li><%= link_to "戻る", :back %></li>
  </ol>
</section>
</div>

app/views/communities/rooms/players/new.html.erb
<div class="container">
<h1>エントリー</h1>
<p>セッションに参加します。</p>
<div class="space01"></div>
<div class="row">
	<div class="col-md-offset-1 col-md-10">
		<section class="widget">
			<%= render 'form' %>
		</section>
	</div>
</div>
<div class="space01"></div>
<section class="widget">
 	<ol class="breadcrumb">
		<li><%= link_to '参加者一覧', community_room_players_path(@community, @room) %></li>
		<li><%= link_to "戻る", :back %></li>
	</ol>
</section>
</div>

app/views/communities/rooms/players/show.html.erb
<div class="container">
		<% if @player.character %>
		<h1><%= @room.name %>参加キャラクター詳細</h1>
<p>セッションで使用する参加キャラクターの詳細です。</p>
<div class="space01"></div>

<div class="row">
	<div class="col-sm-offset-1 col-sm-10 col-xs-12">
		<div class="row">

			<div class="col-sm-3 col-xs-12">
				<p><%= image_tag @player.character.image %></p>
			</div>

			<div class="col-sm-9 col-xs-12">
				<div class="well">
					<p><strong>キャラクター名：</strong><%= @player.character.name unless @player.character.nil? %></p>
					<p><strong>キャラ作成者：</strong><%= @player.character.user.name %></p>
					<p><strong>役割：</strong><%= @player.player_role.name %></p>
				</div>

				<div class="well">
					<p><strong>パラメータ</strong></p>
					<%= @player.character.paramaters %>
				</div>

			</div>
		</div>
		<div class="well">
			<p><strong>説明：</strong><%= @player.character.about %></p>					
			<strong>プロフィール</strong><br />
			<p><%= @player.character.profile.html_safe %></p>

			<strong>ステータス</strong><br />
			<p>ステータスは後日</p>

			<strong>メモ</strong><br />
			<p><%= @player.character.memo.html_safe %></p>
		</div>
	</div>
</div>
<% else %>
	セッションに参加しました<br>
	<%= @player.player_role %>
<% end %>

<div class="space01"></div>
<section class="widget">
 	<ol class="breadcrumb">
		<li><%= link_to '編集', edit_community_room_player_path(@community, @room, @player) %></li>
		<li><%= link_to 'セッション参加者一覧', community_room_players_path(@community, @room) %></li>
		<li><%= link_to "戻る", :back %></li>
	</ol>
</section>
</div>